### PR TITLE
English translation - powered by google translate

### PR DESCRIPTION
**Pull request by Kirottu**
I wanna understand your source code bud :p

### CODE REVIEW

**Comment by arte921** [comment]
lmao that works?
gotta setup a git system which auto translates like that, so we can all code in our own languages. what could possibly go wrong?

**Comment by arte921** [comment]
made a separate dutch and english branch, and deleted master
now we only need it to auto translate

**Comment by Kirottu** [comment]
No there was no automated translation i just had nothing better to do so i went thru it manually.

**Comment by arte921** [comment]
awesome

**Pull request closed without merging**
